matrix:
- name: Python Source
  aspell:
    lang: en
    d: en_US
  sources:
  - dct/*.py
  - tests/*.py
  dictionary:
    wordlists:
      - docs/wordlist
  pipeline:
  - pyspelling.filters.python:
      strings: true
      comments: true
  ignore_regexp:
        - '.*\b(TODO|FIXME|NOTE)\b.*'
- name: markdown
  sources:
  - README.rst
  - CHANGELOG.md
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - docs/wordlist
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: true
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
