matrix:
- name: Python Source
  aspell:
    lang: en
    d: en_US
  sources:
  - dct/*.py
  dictionary:
    wordlists:
      - docs/wordlist
  pipeline:
  - pyspelling.filters.python:
      strings: false
      comments: false
  ignore_regexp:
        - '.*\b(TODO|FIXME|NOTE|:param|:type|:return|:rtype)\b.*'