"""Init python files as modules."""
from dct.mod_zvs import *
from dct.currents import *
from dct.datasets import *
from dct.geckosimulation import *
from dct.sample_requirements import *
from dct.mod_zvs import *
from dct.plot_dab import *
from dct.plot_window import *
from dct.plot_calculation import *
from dct.plot_simulation import *
from dct.plot_waveforms import *
from dct.pareto_dtos import *
from dct.pareto import *
from dct.generalplotsettings import *
from dct.functions_waveforms import *
from dct.datasets_dtos import *
from dct.heat_sink import *
from dct.heat_sink_dtos import *
from dct.plot_masks import *
from dct.losses import *
from dct.toml_checker import *
