[design_space]
    f_s_min_max_list=[50e3, 300e3]
    l_s_min_max_list=[20e-6, 900e-6]
    l_1_min_max_list=[10e-6, 10e-3]
    l_2__min_max_list=[10e-6, 1e-3]
    n_min_max_list=[3, 7]
    transistor_1_name_list=['CREE_C3M0065100J', 'CREE_C3M0120100J']
    transistor_2_name_list=['CREE_C3M0060065J', 'CREE_C3M0120065J']
    c_par_1=16e-12
    c_par_2=16e-12

[output_range]
    v_1_min_nom_max_list=[690, 700, 710]
    v_2_min_nom_max_list=[175, 235, 295]
    p_min_nom_max_list=[-2000, 2000, 2200]
    steps_per_direction=3

[filter_distance]
    delta = [0.1,0.1] # difference (x ,y) 1 = difference between minimal and maximal result value
    range  = [[0.1,0.9],[0.1,0.9]] # Used range of X und Y-axe
    deep = [0.01,0.01] # Max difference to real pareto points (X und Y-direction)
