[InductorConfigName]
    inductor_config_name = "inductor_01"

[Designspace]
    core_name_list = ["PQ 50/50", "PQ 50/40", "PQ 40/40", "PQ 40/30", "PQ 35/35", "PQ 32/30", "PQ 32/20", "PQ 26/25", "PQ 26/20", "PQ 20/20", "PQ 20/16"]
    material_name_list = ["3C95"]
    litz_wire_list = ["1.5x105x0.1", "1.4x200x0.071", "1.1x60x0.1"]

[InsulationData]
    primary_to_primary = 0.2e-3
    core_bot = 1e-3
    core_top = 1e-3
    core_right = 1e-3
    core_left = 1e-3

[FilterDistance]
    Delta = [0.1,0.1] # difference (x ,y) 1 = difference between minimal and maximal result value
    Range = [[0.1,0.9],[0.1,0.9]] # Used range of X und Y-axe
    Deep = [0.01,0.01] # Max difference to real pareto points (X und Y-direction)
